Fixed invalid call to heat.db.api.configure().
Invalid call to heat.db.api.configure() was causing the heat-db-setup
script to error out:

$ sudo heat-db-setup deb -y -r somepass
Installing on a Debian system.
Verified connectivity to MySQL.
Creating 'heat' database.
Traceback (most recent call last):
  File "/usr/lib/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/home/jason/github/heat/heat/db/sync.py", line 35, in <module>
    heat.db.configure()
AttributeError: 'module' object has no attribute 'configure'
ERROR 1146 (42S02) at line 1: Table 'heat.migrate_version' doesn't exist
Final sanity check failed.