Remove package version to fix PBR version error
ValueError: git history requires a target version of
pbr.version.SemanticVersion(2015.1.0.0b2), but target version is
pbr.version.SemanticVersion(5.0.0)

Change-Id: Ib14dc6079fb64c0bc65d6ff3954a34814e92027c